### PR TITLE
noa

### PR DESCRIPTION
**Pull request by noa-kaplan**
Hi Simon,
This is my first pull request so please be informed :)
 I created a simple library to interact with Opentrons liquid handler.
The library is a rapper on our API endpoints. So the user can GET/POST/PUT data from/to Labguru experiments easily.
I'd to get your feedback on the code.
Thanks
Noa

### CODE REVIEW

**Comment by simonweil** [comment]
First of all, this is great!

Only issue is that the PR represents a tiny change while the code is already in master.
I assume you want me to review the code that is already in master, right?

**Comment by simonweil** [comment]
Let's look at it tomorrow together

**Comment by simonweil** [comment]
@noa-kaplan can we close this PR?

**Comment by noa-kaplan** [comment]
> @noa-kaplan can we close this PR?

Yes.

**Pull request closed without merging**
